### ISSUE TITLE
Creating a Nav Bar

### ISSUE THREAD

**Issue by OrangeHoopla** [SpaghettiCoders/WellnessNetworkWebsite#3]
A over arching Nav bar that links to the main webpages

**Comment by andrewghung** [comment]
<img width="958" alt="NavBar" src="https://user-images.githubusercontent.com/36482018/68554156-8cf52100-03f4-11ea-8b6b-16609ef039d0.png">
Functional inside Webflow.
Completed hover micro-interactions. 
Todo: Create focus state interactions, indicating which page the user is currently on.
